database:
  host: "FFGGHHH"
  database_name: "DFFGGGG"
  port: "9876"
  username: "xmplar"
  password: "xFacGHJJt2005"

send_mail_details:
  sender:
    email: "chatbot.xmplar@gmail.com"
    password: "iswokdezruppoqow"
  receiver:
    # - "samvatsar.s@xmplar.in"
    # - "sundar@xmplar.in"
    - "paramesha.m@xmplar.in"

timezone: "Asia/Calcutta"

xmplar_chatbot:
  endpoint: 'https://xmplarchatbot.crest-erp.com:5000'
  bot_name:  "Xmplar chatbot"
  time: "15:40"

creya_chatbot:
  endpoint: 'https://chatbot.crest-erp.com:5000'
  bot_name:  "Creya chatbot"
  time: "15:40"

whatsapp_chatbot:
  endpoint: 'https://xmplarchatbot.crest-erp.com:5001'
  bot_name:  "Whatsapp chatbot"
  time: "15:40"

remove_token_time: "15:40"